### ISSUE TITLE
Failed to load driver class mysql from HikariConfig class classloader

### ISSUE THREAD

**Issue by cw1427** [shzlw/poli#4]
First of all, thanks. That is a very interesting project you made. I setup the mysql driver jar in the jdbc-drivers folder in the project. 

When I added a datasource and ping it works well. And then made a report, it works very well when check the datasorce schema. But when I edit the query to fetch data, it went wrong with this error:

My platform is Windows. And I have already added the mysql driver jar into the java classpath. What I'm curious is it works well for datasource schema read, but failed for query execution, due to driver load failed. Any idea?

2019-06-13 14:56:18 [http-nio-6688-exec-3] ERROR com.zaxxer.hikari.HikariConfig - Failed to load driver class mysql from HikariConfig class classloader org.springframework.boot.loader.LaunchedURLClassLoader@6433a2
2019-06-13 14:56:18 [http-nio-6688-exec-3] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Failed to load driver class mysql in either of HikariConfig class loader or Thread context classloader] with root cause
java.lang.RuntimeException: Failed to load driver class mysql in either of HikariConfig class loader or Thread context classloader
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:485)
	at com.shzlw.poli.service.JdbcDataSourceService.lambda$getDataSource$1(JdbcDataSourceService.java:75)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at com.shzlw.poli.service.JdbcDataSourceService.getDataSource(JdbcDataSourceService.java:65)
	at com.shzlw.poli.rest.JdbcQueryWs.queryComponent(JdbcQueryWs.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by shzlw** [comment]
Thanks for trying Poli out! I tested the MySQL connection locally and here is my setup.

* Operating system: Windows 10
* Database version: MySQL 8.0
* mysql-connector-java-8.0.16.jar under jdbc-drivers folder
* Connection Url: jdbc:mysql://localhost:3306/test
* Driver Class Name: com.mysql.jdbc.Driver

I can run query without problems. The only difference is I don't have the JDBC driver in my classpath. Could you try remove that and only leave the JDBC jar in jdbc-drivers folder?

The reason why ping and show schema work but query doesn't work is because java.sql.Connection is used in ping and show schema query but the actual data query is using HikariDataSource so it seems the former one is picking up your JDBC driver but the latter one doesn't for some reasons. 

I will modify ping and show schema function to use HikariDataSource to be consistent.

**Comment by cw1427** [comment]
@shzlw :
Thanks, my mistake. I took a wrong driver class name. But when I correct it, met a new issue for trial to fetch a table data, got connection leak issue.
BTW, looks like there might be a performance problem when I tried to operate refresh table, the web page stuck a few seconds no response? Or maybe it is the backend connection leak issue lead to.

2019-06-14 12:59:52 [HikariPool-2 housekeeper] WARN  com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@1fd582d1 on thread http-nio-6688-exec-8, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:600)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:657)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:682)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:172)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:180)
	at com.shzlw.poli.service.JdbcQueryService.queryComponentByParams(JdbcQueryService.java:144)
	at com.shzlw.poli.rest.JdbcQueryWs.queryComponent(JdbcQueryWs.java:75)

**Comment by cw1427** [comment]
@shzlw : 
I enlarged the jvm heap and restart the poli, it got fix now.  Thanks!
